[package]
name = "aws-rust-api"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dashmap = "4.0.2"
rand = "0.8.4"
rocket = "0.5.0-rc.1"
